baseURL: "https://www.practivio.com/"  # Update this from localhost if deploying
languageCode: "en-us"
title: "Practivio"
theme: "PaperMod"
pagination:
  pagerSize: 10

params:
  assets:
    favicon: "logo.png"
    logo: "logo.png"
