baseURL: "https://practivio.com"
languageCode: "en-us"
title: "Practivio"
theme: "PaperMod"

params:
  defaultTheme: light
  disableThemeToggle: true
  favicon: "/favicon.ico"
  assets:
    css:
      - "css/custom.css"

menu:
  main:
    - name: "Disclosure"
      url: "/affiliate-disclosure"
      weight: 50
